---
- hosts: k8s-nodes
  remote_user: root
  vars:
   kube_version: 1.16.0-0
  tasks:
   - name: prepare env
     script: ./pre-setup.sh
   - name: install kubeadm, kubelet
     yum: name={{item}} state=present
     with_items:
       - kubeadm-{{kube_version}}
       - kubelet-{{kube_version}}
